# Generated by Django 3.0.8 on 2020-07-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
